language: ruby
rvm: system
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      dist: trusty
      sudo: false

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sudo chown -R $USER "$(brew --repo)";
      git -C "$(brew --repo)" reset --hard origin/master;
      brew update || brew update;
      rm -rf "$(brew --repo $TRAVIS_REPO_SLUG)";
    else
      HOMEBREW="$HOME/.linuxbrew/Homebrew";
      git clone --depth=1 https://github.com/Linuxbrew/brew "$HOMEBREW";
      export PATH="$HOMEBREW/bin:$PATH";
      umask 022;
    fi
  - mkdir -p "$(brew --repo $TRAVIS_REPO_SLUG)"
  - rsync -az "$TRAVIS_BUILD_DIR/" "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export TRAVIS_BUILD_DIR="$(brew --repo $TRAVIS_REPO_SLUG)"
  - cd "$(brew --repo)"
  - ulimit -n 1024

script:
  - brew test-bot

notifications:
  email:
    on_success: never
    on_failure: always
