jobs:
- job: CheckStyle
  pool:
    vmImage: ubuntu-16.04
  container:
    image: homebrew/brew:latest
  steps:
    - bash: |
        git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
        git checkout pr
      condition: ne(variables['System.PullRequest.PullRequestNumber'], '')
      displayName: Checkout pull request
    - bash: |
        sudo cp -a $(Build.Repository.LocalPath) /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev
      displayName: Set up tap
    - bash: |
        /home/linuxbrew/.linuxbrew/bin/brew style $BUILD_REPOSITORY_ID
      displayName: Run brew style
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
