name: Docker
on:
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t homebrew/debian7 .
      - name: Deploy the Docker image to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u brewtestbot -p ${{secrets.DOCKER_TOKEN}}
          docker push homebrew/debian7
